/*
    plang_parser_internal.h
    plang

    Copyright © 2026 Christopher M. Hanson. All rights reserved.
    See the file COPYING for license details.
*/

#ifndef __plang_parser_internal__h__
#define __plang_parser_internal__h__

#include "plang_parser.h"

#include <unistd.h>

PLANG_HEADER_BEGIN


/* Forward Declarations*/

typedef struct plang_dictionary *plang_dictionary_t;


/*!
 The internals of a `plang` parser.
 */
struct plang_parser {
    /*!
     The preamble source to parse into a unit and then use as the
     outermost scope for all subsequent parses.
     */
    plang_source_t PLANG_NULLABLE _preamble_source;

    /*!
     The unit generated by the preamble source.
     */
    plang_unit_t PLANG_NULLABLE _preamble_unit;

    /*!
     All of the sources to parse, in order.

     - TODO: Support multiple sources via $I directive.
     */
    plang_array_t _sources;

    /*!
     The current source code being parsed.

     - TODO: Support multiple sources via $I directive.
     */
    plang_source_t _source;

    /*!
     Current tokenization position within the current source.

     Getting the next token starts from this character index in
     `_source`.

     - TODO: Support multiple sources via $I directive.
     */
    size_t _source_pos;

    /*! All of the scanned tokens, in scan order. */
    plang_array_t _tokens;

    /*! Cached count of the tokens. */
    size_t _tokens_count;

    /*!
     Current parsing position.

     Getting the next non-comment token starts from this token index in
     `_tokens`.
     */
    size_t _token_pos;

    /*! Scope stack for the current parse. */
    plang_array_t _scopes;

    /*! Cache of the top of the scope stack. */
    plang_scope_t PLANG_NULLABLE _current_scope;

    /*! Errors encountered during the current parse. */
    plang_array_t _errors;

    /*! The units parsed, keyed by identifier. */
    plang_dictionary_t _units;

    /*! The program parsed. */
    plang_program_t PLANG_NULLABLE _program;
};


/* MARK: - Character Stream Access */

/*! Get the next character to parse. */
char
plang_get_char(plang_parser_t parser);


/*! Peek at the next character to parse. */
char
plang_peek_char(plang_parser_t parser);


/*! Put back the last character. */
void
plang_unget_char(plang_parser_t parser,
                 char ch);


PLANG_HEADER_END

#endif /* __plang_parser_internal__h__ */
